### ISSUE TITLE
Error immediately after launch

### ISSUE THREAD

**Issue by Xikaro** [NotMyWing/NAE2#1]
![Screenshot_30](https://github.com/NotMyWing/NAE2/assets/55663835/d50e5a2f-44b9-47a0-afdf-e20b5b07f05a)

**Comment by NotMyWing** [comment]
NAE2 depends on https://www.curseforge.com/minecraft/mc-mods/mixin-booter, which has not yet been added as a formal dependency. This, however, will be addressed in the next release.
