### ISSUE TITLE
suggestion: hyper-acceleration card

### ISSUE THREAD

**Issue by serenibyss** [NotMyWing/NAE2#10]
acceleration card but Faster

**Comment by NotMyWing** [comment]
How fast are we talking?

**Comment by serenibyss** [comment]
Default accel card is 2/4/8x, hyper-accel card is 16/128/1024x in 1.7. Though in 1.7 it is limited to only the IO port and fluid import/export buses, not sure if this is for good reason or arbitrary. Originally this card was added just for the IO port and i think 1.7 ae2fc author decided to allow it in the fluid buses

**Comment by NotMyWing** [comment]
Good to go.

Supports only ME IO Ports for now, but if desired, compatibility with more machines can be added later on.
