### ISSUE TITLE
stocking input hatch/bus

### ISSUE THREAD

**Issue by Blocky106** [NotMyWing/NAE2#13]
Like in NH where you can just have these two setup.
its more lag efficient and a lot of people like these two
The stocking input bus would be like combining an input bus and an interface, without an internal buffer, thus you wouldnt have any items buffered inside of it, wich you cannot access,

**Comment by NotMyWing** [comment]
This is already a part of GTCEu, see https://github.com/GregTechCEu/GregTech/commit/ef016408f9f02ba0ddf938c43660b1cdbd5c6790.

If this is a suggestion for GTCE, then unfortunately, there isn't much I can do.
