### ISSUE TITLE
Suggestion: Craft all missing items in JEI/HEI preview

### ISSUE THREAD

**Issue by Niels1006** [NotMyWing/NAE2#15]
Craft all missing items with pressing "ctrl + left click" on "+".

![image](https://github.com/NotMyWing/NAE2/assets/16525967/39396c9c-ea8c-4e9c-a6ac-3037502282c2)

In this example it will bring you to the screen to start a craft for one hv assembly, one hv machine hull and two hv motors.
Useful, because you dont need to order every item "manually" with middle mouse button anymore.

**Comment by NotMyWing** [comment]
Mostly done. Need to polish down some of the sharp edges, but overall coming soon.
