### ISSUE TITLE
Crash with Thaumic Energistics Extended Life

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [NotMyWing/NAE2#21]
Step to reproduce: 
1. Place Thaumic Energistic's microparts
2. Crash

Crash report and log:
[crash-2023-10-25_01.23.45-client.txt](https://github.com/NotMyWing/NAE2/files/13125501/crash-2023-10-25_01.23.45-client.txt)
[latest.log](https://github.com/NotMyWing/NAE2/files/13125498/latest.log)
The crash happen from v1.4.0 to latest

**Comment by NotMyWing** [comment]
The consequences of not matching signatures.

https://legacy.curseforge.com/minecraft/mc-mods/nae2/files/4817142

Should be fixed.
