### ISSUE TITLE
Requieres mixinbooter bug

### ISSUE THREAD

**Issue by NuanKi** [NotMyWing/NAE2#23]
i have a mod that needs mixinbooter 8.3 or above, and i have the 8.8 version and when i try to open the game it says:
You must include the right dependencies
Requieres mixinbooter 8.3 or above (missing)
![image](https://github.com/CleanroomMC/MixinBooter/assets/80914838/b84688c1-cda0-4305-88eb-3c94d5ea9166)
while this is my mods folder
![image](https://github.com/CleanroomMC/MixinBooter/assets/80914838/6cde1ba9-30b0-48da-97c7-5150ac51fa12)
i tried reinstalling this and the mod that needs this, but its the same
This is the latest.log
https://pastebin.com/HUh7MNXw

**Comment by NotMyWing** [comment]
https://github.com/CleanroomMC/MixinBooter/issues/61#issuecomment-1803289892

**Comment by NotMyWing** [comment]
Try seeing if any of the installed mods is interfering with MixinBooter. Since it's not just NAE2 complaining about the dependency, it's very probable that something is preventing MixinBooter from being picked up by Forge.

**Comment by NuanKi** [comment]
<3
