### ISSUE TITLE
Interface P2Ps stalling after world being idle or loaded into

### ISSUE THREAD

**Issue by windyknight** [NotMyWing/NAE2#27]
Pack: Nomifactory CEu 1.7 alpha 1, Normal Mode
Singleplayer world

Where it occurs in my world:
- machines with an Interface P2P and importing cover (conveyor or keep exact robot arm) on top for stocking inputs and controlled by level emitter and machine controller cover on front
- multiblock input bus with an Interface P2P on bottom and filter insert cover to control what gets inputted, and controlled by machine controller cover and level emitter

Expected behavior:
- machine inputs remain full with their respective input ingredient
- input buses automatically import their filtered ingredient

What actually happens:
- machine inputs eventually become empty even if there is stock of their ingredient available
- input buses do not import even when they're active and their filtered input is available

When does this happen: On entering world or leaving it idle for a while

Temporary fixes found: changing the level emitter threshold behavior (whether to emit at above or below threshold) and back lets the attached machine/bus import again

Attempted fixes that do not work: disconnecting and reconnecting the entire system via removing and replacing the nearby ME conduit does not fix the problem

Do other Interface type items work: Regular interfaces and Phantomfaces (Actually Additions) work properly on world loads and do not appear to face this bug

Replicability on test world: Currently unable to replicate

Demonstration videos:

https://github.com/NotMyWing/NAE2/assets/9163117/3c780a4f-8413-4408-ab3b-d4d341036464

https://github.com/NotMyWing/NAE2/assets/9163117/1c320fb9-c110-4141-868c-eeb50a15698a

World file link (main world):
https://drive.google.com/file/d/1oXo2gDX3gw6Ui199dcrbXtfM7n3a4frK/view?usp=sharing

In the zip, "new city" is the world folder, while "addl-mods" contains the additional mods I use that are not part of the pack modlist, including the updated version of NAE2 with Interface P2Ps.

What to look for in the world: 
- In the PPC setup that the player should be standing near, look for machines that have stopped due to empty input or whose inputs are not full and slowly draining.
- Check if there is Resonant Clathrate available in the stocking interfaces for the stopped input bus.
- Confirm if they run again when doing the temporary fix described above with their respective level emitter.
- The way the system is currently set up, there should be a stock of all ingredients except Resonant Clathrate which gets smelted immediately.

**Comment by NotMyWing** [comment]
Thanks for a very in-depth analysis! Will investigate. I have some clues already as to why and how this might be happening, though it's very bizarre since most of the logic is based directly on regular item tunnels.

**Comment by Legend2579** [comment]
I've encountered this bug too in another GTCE pack with single block and multiblock machines. I have a line of 16 electrolyzers connected with N:N P2P interfaces that I use to break down most ore byproducts. Sometimes what happens is that most of the machines will turn on and start working, but not all of them. In order for the idle ones to start working I'll have to open up their GUI and click on any button, then it starts pulling items and working properly. For the multiblocks it's a similar scenario. The input buses sometimes stop auto pulling from P2P interfaces until they are rotated or broken and replaced.
