### ISSUE TITLE
no

### ISSUE THREAD

**Issue by 15736865855** [NotMyWing/NAE2#6]
Not Supported AE2 Unofficial Extended
https://github.com/beecupbe/ae2uel_extended
https://legacy.curseforge.com/minecraft/mc-mods/ae2-uel-extended

**Comment by NotMyWing** [comment]
I'll take a look, but I can't guarantee interoperability since the mod targets AE2:EL specifically.

**Comment by aking4125** [comment]
Version 1.4.0 works with AE2:UEL Extended. 

Versions 1.4.1 and above result in the above conflict.

Using 1.4.0 seems to work flawlessly on our server without any issues thus far.

**Comment by NotMyWing** [comment]
This is because 1.4.1 ships with a strict AE2:EL version requirement to prevent the mod running with the original AE2. A workaround is planned to be shipped with the next release.
