### ISSUE TITLE
suggestion: advanced blocking card

### ISSUE THREAD

**Issue by serenibyss** [NotMyWing/NAE2#9]
Upgrade card to go into interfaces, which will cause blocking mode to block on any item present in the network. in 1.7, the advanced blocking card goes into the receiver interface in a kissing interface setup, not the sender interface

**Comment by NotMyWing** [comment]
This is fairly easy to integrate into the current blocking mode injection.

However, doesn't it make more sense for it to go into the sender Interface instead, since it's the part that does the checking?

**Comment by NotMyWing** [comment]
To my surprise, this is already a part of AE2:EL. Blocking mode natively reads subnets, however blocking mode exclusions don't get any special treatment.

I might or might not contribute this. Depends on how really useful this is.
